import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "secondary-fixed": "#e3e2df",
        "on-secondary-container": "#626360",
        "surface-bright": "#f8f9ff",
        "on-primary-container": "#7c839b",
        "surface-container-high": "#dde9ff",
        "primary-fixed-dim": "#bec6e0",
        "secondary-fixed-dim": "#c7c7c3",
        "on-primary-fixed-variant": "#3f465c",
        "surface-variant": "#d5e3fd",
        "inverse-surface": "#233144",
        "on-tertiary-container": "#9f7e57",
        "primary": "#000000",
        "on-secondary-fixed-variant": "#464744",
        "on-error": "#ffffff",
        "on-background": "#0d1c2f",
        "surface-container-highest": "#d5e3fd",
        "on-tertiary": "#ffffff",
        "on-secondary": "#ffffff",
        "surface-tint": "#565e74",
        "outline-variant": "#c6c6cd",
        "on-surface": "#0d1c2f",
        "tertiary-container": "#2a1700",
        "primary-fixed": "#dae2fd",
        "on-tertiary-fixed": "#2a1700",
        "on-surface-variant": "#45464d",
        "tertiary-fixed-dim": "#e6c094",
        "secondary-container": "#e0e0dc",
        "on-error-container": "#93000a",
        "surface": "#f8f9ff",
        "on-secondary-fixed": "#1b1c1a",
        "surface-container-lowest": "#ffffff",
        "on-primary": "#ffffff",
        "error-container": "#ffdad6",
        "surface-container": "#e6eeff",
        "surface-container-low": "#eff4ff",
        "inverse-primary": "#bec6e0",
        "on-tertiary-fixed-variant": "#5c4220",
        "tertiary": "#000000",
        "inverse-on-surface": "#ebf1ff",
        "surface-dim": "#ccdbf4",
        "secondary": "#5e5f5c",
        "primary-container": "#131b2e",
        "tertiary-fixed": "#ffddb7",
        "outline": "#76777d",
        "error": "#ba1a1a",
        "background": "#f8f9ff",
        "on-primary-fixed": "#131b2e",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      spacing: {
        "section-gap": "120px",
        "margin-edge": "64px",
        base: "8px",
        gutter: "32px",
        "container-max": "1440px",
      },
      fontFamily: {
        "body-md": ["var(--font-manrope)"],
        "headline-lg": ["var(--font-noto-serif)"],
        "label-caps": ["var(--font-manrope)"],
        "body-lg": ["var(--font-manrope)"],
        "headline-md": ["var(--font-noto-serif)"],
        "display-xl": ["var(--font-noto-serif)"],
      },
      fontSize: {
        "body-md": ["16px", { lineHeight: "1.6", fontWeight: "400" }],
        "headline-lg": ["48px", { lineHeight: "1.2", fontWeight: "400" }],
        "label-caps": ["12px", { lineHeight: "1.2", letterSpacing: "0.1em", fontWeight: "600" }],
        "body-lg": ["18px", { lineHeight: "1.7", fontWeight: "400" }],
        "headline-md": ["32px", { lineHeight: "1.3", fontWeight: "400" }],
        "display-xl": ["80px", { lineHeight: "1.1", letterSpacing: "-0.02em", fontWeight: "300" }],
      },
    },
  },
  plugins: [],
};
export default config;
